# Generated by Django 4.1.1 on 2022-09-14 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=25, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=25, verbose_name="Last name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="email address"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone number")),
                (
                    "mobile",
                    models.CharField(max_length=20, verbose_name="Mobile number"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=20, verbose_name="Company"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.BooleanField(
                        default=False, verbose_name="Has contract been signed ?"
                    ),
                ),
                (
                    "amount",
                    models.FloatField(max_length=11, verbose_name="Contract amount"),
                ),
                ("payment_due", models.DateTimeField(verbose_name="Payment due date")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.BooleanField(default=True, verbose_name="Event status"),
                ),
                (
                    "attendees",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Event Attendees",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Event date")),
                (
                    "notes",
                    models.TextField(max_length=1000, verbose_name="Additional notes"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EpicEventsAPI.client",
                    ),
                ),
            ],
        ),
    ]
