# Generated by Django 4.1.1 on 2022-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EpicEventsAPI", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
