# Generated by Django 4.1.1 on 2022-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EpicEventsAPI", "0002_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                max_length=100, unique=True, verbose_name="email address"
            ),
        ),
    ]
