# Generated by Django 4.1.1 on 2022-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EpicEventsAPI", "0003_alter_client_date_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="date_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
