# Generated by Django 4.1.1 on 2022-09-14 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EpicEventsAPI", "0005_alter_event_attendees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company_name",
            field=models.CharField(max_length=20, verbose_name="Company"),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=25, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=25, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(max_length=20, verbose_name="Mobile number"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="amount",
            field=models.FloatField(max_length=11, verbose_name="Contract amount"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_due",
            field=models.DateTimeField(verbose_name="Payment due date"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.BooleanField(
                default=False, verbose_name="Has contract been signed ?"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Event Attendees",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(verbose_name="Event date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(max_length=1000, verbose_name="Additional notes"),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Event status"),
        ),
    ]
